### ISSUE TITLE
Enable/Disable Run button based on compiling status

### ISSUE THREAD

**Issue by rlawisch** [rlawisch/DynamicBranchPrediction#5]
Run button should start disabled and be enabled after compiling. When the code inside `textEdit_` gets changed, the button should be disabled again.

My suggestion:
	- Do some referencing to the button in main window
	- Make the button start disabled by default
	- Create a variable to store the last compiled code plain text
	- Make Compile action set the text content and enable run button
	- Create an OnChange event for the `textEdit_` with run button->setEnable(actualCode == lastCompiledCode)

**Comment by leonardo-s-dutra** [comment]
Closing issue.
